### PR TITLE
ember-frost-sort issue cleanup

### PR DESCRIPTION
**Pull request by oadeojo**
# minor
# Changelog
- Deprecated `sortParams` in favor of `sortOrder` and `sortableProperties` in favor of `properties`
- Fixed: https://github.com/ciena-frost/ember-frost-sort/issues/15
  https://github.com/ciena-frost/ember-frost-sort/issues/13
- Fixed bug introduced from the ability to remove frost-sort-items in any order

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/29/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

Can you updat e the tests as well?

**Comment by juwara0** [comment]
We should also update the integration tests. I saw a couple of place in this test file: https://github.com/oadeojo/ember-frost-sort/blob/master/tests/integration/components/frost-sort-test.js#L12

What do we want to update the README with?

**Comment by rox163** [comment]
Ah yes README should have the new props in the API section and a Deprecation section mentioning the old props.

**Comment by rox163** [comment]
@oadeojo please make the changes mentioned in the comments above before merging :)

**Comment by oadeojo** [comment]
@rox163 I had other fixes to push into this PR.

**Comment by rox163** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/29/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

**Pull request merged**
