### PR TITLE
Use correct size icon

### PR DESCRIPTION
**Pull request by sophypal**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

screen shot 2017-12-13 at 9 43 02 am

# CHANGELOG

* Updated icon size to match UX specs

### CODE REVIEW

**Review by notmessenger — APPROVED** [review]
We have generally been avoiding checking in the _package-lock.json_ file until the repos specifically require/support Node >= 8.2

**Comment by notmessenger** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/83/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

**Comment by sophypal** [comment]
Ok, I'll remove it.

**Comment by sophypal** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/83/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

**Pull request merged**
