### PR TITLE
changed sortParams to sortOrder and sortableProperties to properties

### PR DESCRIPTION
**Pull request by oadeojo**
# major
# Changelog
- Changed `sortParams` to `sortOrder` and `sortableProperties` to `properties`

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

**Comment by sglanzer-fire** [comment]
I'd prefer to see this change done as an alias with deprecation notices, this would allow us to avoid a #major#

**Comment by sglanzer-fire** [comment]
Rejected - please go with deprecations and aliases

**Comment by rox163** [comment]
Will it still be a major release in that case?

**Comment by sglanzer-fire** [comment]
Nope, we can do #minor# then

**Pull request closed without merging**
