### PR TITLE
Fixing unique id issues for embedded select components

### PR DESCRIPTION
**Pull request by oadeojo**
# minor

Fixing unique id issues for embedded select components

### CODE REVIEW

**Comment by rox163** [comment]
#minor or major change? Might break implementations parsing the id.

**Comment by oadeojo** [comment]
@rox163 It's a patch. I fixed the description to show that it's a patch.

**Comment by EWhite613** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

**Comment by oadeojo** [comment]
I believe this is actually a minor change so I updated the PR description and kicked off a new build.

**Comment by quincyle** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-sort/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-sort)

**Pull request merged**
